# -*- coding: utf-8 -*-
"""Page copy for the /cabs/ section. One dict per page. Facts researched 30 Sep 2026 (see research/README.md)."""

L = lambda path, label, small="": (path, label, small)

HP_ENTRY = ("Himachal entry fee", "Cars registered outside Himachal pay an entry fee at the state barrier (₹100 a day for passenger vehicles up to 12 seats in 2026–27; commercial and larger vehicles pay more). It is added to your quote at actuals. Details: <a href=\"/himachal-entry-tax-permits-2026/\">Himachal entry tax & permits 2026</a>.")
NIGHT = ("No night driving in the hills", "For safety our drivers do not run hill sections late at night. Leave early (5–6 am from Delhi) and plan to reach before dark; the quote tells you the best start time.")
WINTER = ("Snow months need a plan", "From mid-December to February roads above Shimla and Manali can close after fresh snow. Drivers carry chains; sometimes the last stretch is done in a local 4×4. We confirm the day before.")
MONSOON = ("Monsoon caution", "Mid-July to August brings landslides on hill highways. We watch road advisories and move your start time or route when needed — no extra charge for a route change we suggest.")

PAGES = [
# ------------------------------------------------------------------ DELHI -> SHIMLA
dict(slug="delhi-to-shimla-taxi", kind="route", route="delhi-to-shimla-taxi",
 title="Delhi to Shimla Taxi", seo_title="Delhi to Shimla Taxi from ₹4,899 | One-Way & Round Trip",
 seo_desc="Book a Delhi to Shimla taxi: sedan from ₹4,899 one-way, Innova Crysta & Tempo Traveller too. 345 km, 7–8 hrs via Chandigarh. Quote on WhatsApp in minutes.",
 focus="delhi to shimla taxi",
 kicker="Delhi → Shimla · One-way & round trip",
 tag="Delhi to Shimla by private taxi, door to door",
 sub="Pickup from your home, hotel, IGI Airport or any Delhi station. A hill-experienced driver, an AC car and one clear price before you pay.",
 answer="A Delhi to Shimla taxi covers about <b>345 km in 7–8 hours</b> via Karnal, Ambala, Chandigarh (Zirakpur), Kalka and Solan. One-way fares start around <b>₹4,899 for a sedan</b> and <b>₹8,299 for an Innova Crysta</b>; tolls, parking and the Himachal entry fee are extra at actuals. Leave Delhi by 6 am to reach Shimla by early afternoon.",
 facts=[("Distance","345 km"),("Drive time","7–8 hrs"),("Route","NH44 → NH5"),("Altitude","216 m → 2,205 m"),("Best start","5–6 am"),("Sedan from","₹4,899 one-way")],
 stops=[("Delhi","Pickup from home, hotel, IGI Airport, New Delhi / Nizamuddin / Anand Vihar or ISBT."),
        ("Murthal","Famous dhabas for a parantha breakfast, 45 km out."),
        ("Karnal · Kurukshetra","Fast six-lane NH44; short tea stop if you like."),
        ("Ambala · Zirakpur","The highway skirts Chandigarh at Zirakpur and turns for the hills."),
        ("Kalka · Parwanoo","Himachal border. The climb starts here; entry fee is paid at the barrier."),
        ("Dharampur · Solan","Kasauli is a 12 km detour from Dharampur; Solan for lunch."),
        ("Shimla","Drop at your hotel. Cars cannot enter the Mall & Ridge — we drop at the nearest road point.")],
 map=dict(path=["Delhi","Panipat","Karnal","Ambala","Zirakpur","Kalka","Solan","Shimla"], labels=["Delhi","Karnal","Ambala","Chandigarh","Kalka","Solan","Shimla"], ctx=["Chandigarh","Manali","Dehradun","Kasauli"]),
 tips=[HP_ENTRY,NIGHT,("Shimla's sealed roads","Vehicles are not allowed on the Mall Road, Ridge and some core lanes. Hotels there are reached on foot or by lift from the nearest drop point; porters are available."),("Add Kasauli or Chail","A same-route stop at Kasauli, Chail or Kufri adds only 1–3 hours. Tell us and we'll build it into one fare."),WINTER],
 faqs=[("How much is a taxi from Delhi to Shimla?","One-way fares start around ₹4,899 for a sedan, ₹5,899 for an Ertiga and ₹8,299 for an Innova Crysta. A 12-seater Tempo Traveller starts around ₹11,099. Tolls, parking and the Himachal entry fee are extra at actuals, and peak-season dates cost more."),
       ("How long does Delhi to Shimla take by car?","About 7–8 hours for 345 km, including a breakfast stop. Friday evenings and holiday weekends can add 2–3 hours of traffic near Zirakpur and Parwanoo."),
       ("Can I book a one-way drop from Delhi to Shimla?","Yes. One-way is our most booked option. The fare already covers the car's empty return, so there are no hidden return charges."),
       ("What is the best time to leave Delhi for Shimla?","Between 5 and 6 am. You clear Delhi before traffic, have breakfast at Murthal and reach Shimla by 1–2 pm, well before dark on the hill section."),
       ("Can the taxi drop me at my hotel on Mall Road?","Cars are not allowed on the Mall Road and Ridge. The driver drops you at the nearest permitted point (usually Lift, Victory Tunnel or Cart Road) and you walk or take the lift up."),
       ("Is a round trip or a multi-day Shimla–Manali tour possible?","Yes. For round trips and tours we charge per kilometre with a 250 km daily minimum plus ₹400 a night driver allowance. A 5–6 day Delhi–Shimla–Manali–Delhi circuit in a sedan usually works out cheaper than two one-way drops."),
       ("Do you have Innova Crysta and Tempo Traveller for Shimla?","Yes — hatchback, sedan, Ertiga, Kia Carens, Innova Crysta, 12–14 seat Tempo Traveller and Force Urbania.")],
 related=[L("/shimla/","Shimla travel guide"),L("/best-time-to-visit-shimla/","Best time to visit Shimla"),L("/tours/shimla-manali-tour-package-from-delhi/","Shimla–Manali tour from Delhi","Hotel + cab package"),L("/himachal-tour-packages/","All Himachal packages")],
 wa="Hi Suzu Travels, I need a Delhi to Shimla taxi. Date: ___ , people: ___ , one-way / round trip: ___"),

# ------------------------------------------------------------------ DELHI -> MANALI
dict(slug="delhi-to-manali-taxi", kind="route", route="delhi-to-manali-taxi",
 title="Delhi to Manali Taxi", seo_title="Delhi to Manali Taxi from ₹7,599 | One-Way Cab Booking",
 seo_desc="Delhi to Manali taxi: sedan from ₹7,599, Innova Crysta from ₹12,999 one-way. 540 km via the new Kiratpur–Mandi four-lane. Hill drivers, WhatsApp quote.",
 focus="delhi to manali taxi",
 kicker="Delhi → Manali · Via the new four-lane",
 tag="Delhi to Manali by taxi, in one easy day",
 sub="540 km through Chandigarh, the Kiratpur–Nerchowk tunnels, Mandi and Kullu. Early start, safe hill driver, one fixed price.",
 answer="A Delhi to Manali taxi drives about <b>540 km in 11–13 hours</b> via Chandigarh, Kiratpur Sahib, the Kiratpur–Nerchowk four-lane, Mandi and Kullu. One-way fares start around <b>₹7,599 for a sedan</b>, <b>₹9,199 for an Ertiga</b> and <b>₹12,999 for an Innova Crysta</b>, with tolls and the Himachal entry fee extra. Start by 5 am to reach Manali before dark.",
 facts=[("Distance","540 km"),("Drive time","11–13 hrs"),("Route","NH44 → NH205 → NH3"),("Altitude","216 m → 2,050 m"),("Best start","4:30–5 am"),("Sedan from","₹7,599 one-way")],
 stops=[("Delhi","Early pickup (4:30–5 am) from home, hotel, airport or station."),
        ("Ambala · Chandigarh","Breakfast near Zirakpur or Kharar."),
        ("Ropar · Kiratpur Sahib","Enter the Kiratpur–Nerchowk four-lane with its long tunnels."),
        ("Bilaspur · Sundernagar","The four-lane bypasses the towns; fewer hairpins than the old road."),
        ("Mandi","Lunch by the Beas; the valley road begins."),
        ("Pandoh · Aut tunnel","Pandoh dam and the 2.8 km Aut tunnel into Kullu valley."),
        ("Kullu · Manali","Drop at your Manali hotel, Old Manali or Vashisht.")],
 map=dict(path=["Delhi","Karnal","Ambala","Kharar","Ropar","Kiratpur Sahib","Bilaspur","Sundernagar","Mandi","Aut","Kullu","Manali"], labels=["Delhi","Ambala","Chandigarh","Kiratpur","Mandi","Kullu","Manali"], ctx=["Shimla","Dharamshala","Dehradun"]),
 tips=[NIGHT,HP_ENTRY,("Local sightseeing in Manali","Solang, Atal Tunnel–Sissu and Rohtang trips are done in Manali-registered local taxis (union practice). We book those for you at union rates — see <a href=\"/cabs/manali-taxi-service/\">Manali taxi service</a>."),("Break the journey?","Families with small children often stop a night in Mandi or Kullu, or go Delhi → Shimla → Manali. Ask for a split itinerary."),WINTER,MONSOON],
 faqs=[("What is the Delhi to Manali taxi fare?","One-way starts around ₹7,599 for a sedan, ₹9,199 for an Ertiga, ₹10,299 for a Kia Carens and ₹12,999 for an Innova Crysta. A 12-seater Tempo Traveller starts around ₹17,299. Tolls, parking and the Himachal entry fee are extra at actuals."),
       ("How many hours from Delhi to Manali by taxi?","11–13 hours for about 540 km with breakfast and lunch stops. The Kiratpur–Nerchowk four-lane has cut 2–3 hours off the old road through Bilaspur."),
       ("Is it better to leave Delhi at night for Manali?","We don't recommend it. The last 180 km is mountain road and night driving there is riskier. A 4:30–5 am start gets you to Manali by early evening."),
       ("Can the same taxi take us to Solang and Rohtang?","Local sightseeing around Manali is done in Manali-registered taxis as per local union practice. We book that local taxi for you at union rates, so you don't have to bargain."),
       ("Do you offer Delhi to Manali round trips?","Yes. A round trip or tour is billed per kilometre (250 km daily minimum) plus driver allowance. A 6-day Delhi–Manali–Delhi trip with a Shimla stop is our most booked cab tour."),
       ("Which car is best for Delhi to Manali?","A sedan for 2–3 people with light bags; an Ertiga or Innova Crysta for families and heavy luggage; a Tempo Traveller for 8 or more people.")],
 related=[L("/manali/","Manali travel guide"),L("/delhi-to-manali-budget-trip/","Delhi to Manali budget trip"),L("/tours/attractive-manali-tour-package-from-delhi/","Manali package from Delhi","Hotel + cab"),L("/adventure/snow-activities-manali/","Snow activities in Manali")],
 wa="Hi Suzu Travels, I need a Delhi to Manali taxi. Date: ___ , people: ___ , one-way / round trip: ___"),

# ------------------------------------------------------------------ CHANDIGARH -> MANALI
dict(slug="chandigarh-to-manali-taxi", kind="route", route="chandigarh-to-manali-taxi",
 title="Chandigarh to Manali Taxi", seo_title="Chandigarh to Manali Taxi from ₹4,499 | Fixed Fare",
 seo_desc="Chandigarh to Manali taxi from ₹4,499 (sedan) one-way. Airport, railway station & Tricity pickup. 290 km, 7–8 hrs via the Kiratpur–Mandi four-lane.",
 focus="chandigarh to manali taxi",
 kicker="Chandigarh → Manali · Airport & station pickup",
 tag="Chandigarh to Manali taxi, fixed fare, no surprises",
 sub="Pickup at Chandigarh airport (IXC), railway station, ISBT-43 or anywhere in Mohali, Panchkula and Zirakpur. Seven to eight hours to the snow line.",
 answer="A Chandigarh to Manali taxi covers about <b>290 km in 7–8 hours</b> via Kharar, Ropar, Kiratpur Sahib, the Kiratpur–Nerchowk four-lane, Mandi and Kullu. One-way fares start around <b>₹4,499 for a sedan</b>, <b>₹5,499 for an Ertiga</b> and <b>₹7,699 for an Innova Crysta</b>. Tolls (roughly ₹350–500 for a car) and the Himachal entry fee are extra.",
 facts=[("Distance","~290 km"),("Drive time","7–8 hrs"),("Route","Kiratpur–Nerchowk 4-lane"),("Pickup","IXC · station · Tricity"),("Best start","6–7 am"),("Sedan from","₹4,499 one-way")],
 stops=[("Chandigarh","Airport, railway station, ISBT-43/17, Mohali, Panchkula or Zirakpur."),
        ("Kharar · Ropar","Out of the Tricity towards Kiratpur."),
        ("Kiratpur Sahib","Start of the four-lane with five long tunnels."),
        ("Sundernagar · Mandi","Tea at Sundernagar lake or lunch in Mandi."),
        ("Pandoh · Aut","Pandoh dam, then the Aut tunnel into Kullu valley."),
        ("Bhuntar · Kullu","Kullu airport at Bhuntar; river rafting stretches start here."),
        ("Manali","Drop at your hotel in Manali, Old Manali, Vashisht or Solang road.")],
 map=dict(path=["Chandigarh","Kharar","Ropar","Kiratpur Sahib","Bilaspur","Sundernagar","Mandi","Aut","Kullu","Manali"], labels=["Chandigarh","Kiratpur","Sundernagar","Mandi","Kullu","Manali"], ctx=["Shimla","Dharamshala","Kasol"]),
 tips=[("Flights into Chandigarh","If you land at IXC by noon you can still reach Manali before dark. Later flights: stay the night in Chandigarh or Mandi — we'll suggest the safer plan."),HP_ENTRY,NIGHT,("Manali local taxis","Solang, Atal Tunnel and Rohtang sightseeing runs in Manali-registered taxis. We book them at union rates on the same WhatsApp chat."),WINTER],
 faqs=[("What is the taxi fare from Chandigarh to Manali?","One-way starts around ₹4,499 for a sedan, ₹5,499 for an Ertiga, ₹6,099 for a Kia Carens and ₹7,699 for an Innova Crysta. A 12-seater Tempo Traveller starts around ₹10,299. Tolls, parking and the Himachal entry fee are extra at actuals."),
       ("How long is the drive from Chandigarh to Manali?","About 7–8 hours for roughly 290 km on the new Kiratpur–Nerchowk four-lane, including a meal stop. Weekend traffic near Kullu can add an hour."),
       ("Can you pick me up from Chandigarh airport?","Yes. The driver waits at IXC arrivals with your name. Share the flight number and we track delays at no extra cost."),
       ("Is Manali to Chandigarh available too?","Yes, the same fares apply for Manali to Chandigarh drops, including drops at Chandigarh airport and railway station."),
       ("Can we stop at Kasol or Manikaran on the way?","Yes — Kasol is a 30 km detour from Bhuntar. Add it when you book and we'll quote one fare."),
       ("Is a Chandigarh–Shimla–Manali tour possible in one cab?","Yes. Multi-day tours are billed per kilometre (250 km daily minimum) plus driver allowance; it's usually cheaper than separate one-way drops.")],
 related=[L("/tours/manali-tour-package-from-chandigarh/","Manali package from Chandigarh","Hotel + cab"),L("/tours/shimla-manali-tour-package-from-chandigarh/","Shimla–Manali from Chandigarh"),L("/manali/","Manali travel guide"),L("/manali-in-october-vs-november-which-month-should-you-choose/","Manali in Oct vs Nov")],
 wa="Hi Suzu Travels, I need a Chandigarh to Manali taxi. Pickup (airport/station/address): ___ , date: ___ , people: ___"),

# ------------------------------------------------------------------ CHANDIGARH -> SHIMLA
dict(slug="chandigarh-to-shimla-taxi", kind="route", route="chandigarh-to-shimla-taxi",
 title="Chandigarh to Shimla Taxi", seo_title="Chandigarh to Shimla Taxi from ₹2,299 | Airport Pickup",
 seo_desc="Chandigarh to Shimla taxi from ₹2,299 one-way. 115 km, 3–3.5 hrs via Kalka & Solan. Airport, station & Tricity pickup; Kasauli or Kufri add-on on request.",
 focus="chandigarh to shimla taxi",
 kicker="Chandigarh → Shimla · 3 hours to the hills",
 tag="Chandigarh to Shimla taxi, in about three hours",
 sub="The quickest hill escape from the Tricity. Pickup from IXC airport, the railway station or your door; add Kasauli, Chail or Kufri on the way.",
 answer="A Chandigarh to Shimla taxi covers about <b>115 km in 3–3.5 hours</b> via Zirakpur, Pinjore, Kalka–Parwanoo and the four-lane to Solan. One-way fares start around <b>₹2,299 for a sedan</b>, <b>₹2,999 for an Ertiga</b> and <b>₹3,999 for an Innova Crysta</b>, plus tolls and the Himachal entry fee at actuals. Same-day return trips with Kufri are popular too.",
 facts=[("Distance","~115 km"),("Drive time","3–3.5 hrs"),("Route","NH5 via Solan"),("Pickup","IXC · station · Tricity"),("Add-ons","Kasauli · Kufri · Chail"),("Sedan from","₹2,299 one-way")],
 stops=[("Chandigarh","Airport, railway station, ISBT, Mohali, Panchkula or Zirakpur."),
        ("Pinjore","Mughal-era Pinjore gardens, 20 km out."),
        ("Kalka · Parwanoo","Himachal border and the Timber Trail ropeway."),
        ("Dharampur","Turn-off for Kasauli (12 km) and the Kalka–Shimla toy-train line."),
        ("Solan · Kandaghat","Chail is a 30 km detour from Kandaghat."),
        ("Shimla","Drop at the nearest road point to your hotel.")],
 map=dict(path=["Chandigarh","Kalka","Parwanoo","Dharampur","Solan","Kandaghat","Shimla"], labels=["Chandigarh","Kalka","Dharampur","Solan","Shimla"], ctx=["Kasauli","Chail","Kufri","Narkanda"]),
 tips=[HP_ENTRY,("Kasauli, Chail, Kufri","Each adds 1–3 hours. Tell us when you book and we fold it into one fare."),("Shimla's sealed roads","The Mall and Ridge are car-free. We drop at the nearest allowed point and help with porters if your hotel is uphill."),("Weekend traffic","Friday evening and Sunday afternoon queues at Parwanoo can add 1–2 hours; an early start avoids them."),WINTER],
 faqs=[("How much is a taxi from Chandigarh to Shimla?","One-way starts around ₹2,299 for a sedan, ₹2,999 for an Ertiga, ₹3,499 for a Kia Carens and ₹3,999 for an Innova Crysta. Tolls, parking and the Himachal entry fee are extra at actuals."),
       ("How long does Chandigarh to Shimla take?","About 3–3.5 hours for 115 km. Add 1–2 hours on busy weekends."),
       ("Can I do Chandigarh to Shimla and back in one day?","Yes. A same-day return with Kufri or the Mall is common; it's billed as a local round trip. Ask for the day-trip fare."),
       ("Do you pick up from Chandigarh airport and railway station?","Yes, from IXC arrivals, Chandigarh railway station, Kalka station, ISBT-43 and any address in Mohali, Panchkula or Zirakpur."),
       ("Is Shimla to Chandigarh the same price?","Yes, the same fares apply in reverse, including drops at Chandigarh airport."),
       ("Can we add Kasauli on the way?","Yes, Kasauli is a short detour from Dharampur. Most people add 2–3 hours for Christ Church and Sunset Point.")],
 related=[L("/tours/memorable-chandigarh-shimla-tour-package/","Chandigarh–Shimla package"),L("/shimla/","Shimla travel guide"),L("/best-time-to-visit-shimla/","Best time to visit Shimla"),L("/cabs/shimla-taxi-service/","Shimla local taxi service")],
 wa="Hi Suzu Travels, I need a Chandigarh to Shimla taxi. Pickup: ___ , date: ___ , people: ___"),

# ------------------------------------------------------------------ DELHI <-> CHANDIGARH
dict(slug="delhi-to-chandigarh-taxi", kind="route", route="delhi-to-chandigarh-taxi",
 title="Delhi to Chandigarh Taxi", seo_title="Delhi to Chandigarh Taxi from ₹2,999 | One-Way Cab",
 seo_desc="Delhi to Chandigarh one-way taxi from ₹2,999 (sedan). Also Chandigarh to Delhi & IGI Airport drops. 250 km, 4–5 hrs on NH44. Instant WhatsApp quote.",
 focus="delhi to chandigarh taxi",
 kicker="Delhi ⇄ Chandigarh · One-way both ways",
 tag="Delhi ⇄ Chandigarh one-way taxi, airport to airport",
 sub="IGI Airport, Delhi stations, Gurugram and Noida to Chandigarh, Mohali, Panchkula and IXC — and back. Pay one-way, not return.",
 answer="A Delhi to Chandigarh taxi covers about <b>250 km in 4–5 hours</b> on the NH44 via Murthal, Panipat, Karnal and Ambala. One-way fares start around <b>₹2,999 for a sedan</b>, <b>₹3,699 for an Ertiga</b> and <b>₹5,099 for an Innova Crysta</b>; tolls are extra at actuals. The same fares apply for Chandigarh to Delhi and Chandigarh to IGI Airport drops.",
 facts=[("Distance","~250 km"),("Drive time","4–5 hrs"),("Road","NH44, six-lane"),("Airports","DEL ⇄ IXC"),("Also","Chandigarh → Delhi"),("Sedan from","₹2,999 one-way")],
 stops=[("Delhi / Gurugram / Noida","Home, hotel, IGI T1/T3, New Delhi, Nizamuddin or Anand Vihar."),
        ("Murthal","Dhaba breakfast stop, 45 km out."),
        ("Panipat · Karnal","Six-lane highway; Karnal's Karna Lake is a quick break."),
        ("Kurukshetra · Ambala","Ambala Cantt pickups and drops possible."),
        ("Zirakpur","Gateway to the Tricity."),
        ("Chandigarh · Mohali · Panchkula","Door drop anywhere in the Tricity or at IXC airport.")],
 map=dict(path=["Delhi","Murthal","Panipat","Karnal","Kurukshetra","Ambala","Zirakpur","Chandigarh"], labels=["Delhi","Panipat","Karnal","Ambala","Chandigarh"], ctx=["Shimla","Dehradun","Kalka"]),
 tips=[("Flight connections","For IGI departures we plan a 1.5-hour buffer on top of drive time. Share the flight number and we'll set the pickup time."),("Tolls","There are several toll plazas on NH44; they're paid at actuals and shown in your quote."),("Onward to the hills","Going on to Shimla, Kasauli or Manali? Book the whole trip as one — it's cheaper than two drops."),("Ambala & Kalka stations","We also pick up from Ambala Cantt and Kalka railway stations for hill drops.")],
 faqs=[("What is the one-way taxi fare from Delhi to Chandigarh?","Sedans start around ₹2,999, hatchbacks around ₹2,599, Ertiga around ₹3,699 and Innova Crysta around ₹5,099. Tolls are extra at actuals."),
       ("Is the Chandigarh to Delhi fare the same?","Yes — the same one-way fares apply from Chandigarh, Mohali or Panchkula to anywhere in Delhi NCR, including IGI Airport."),
       ("How long does Delhi to Chandigarh take by taxi?","4–5 hours for about 250 km on NH44, depending on traffic when leaving Delhi."),
       ("Do you do Chandigarh to Delhi airport drops?","Yes, to IGI T1, T2 and T3. We add a buffer for check-in and track your flight time."),
       ("Can I book a hatchback for Delhi to Chandigarh?","Yes, a hatchback is the cheapest option for 1–3 people with light luggage."),
       ("Can the taxi continue to Shimla or Manali?","Yes. Book Delhi → Shimla or Delhi → Manali directly and save on the second leg.")],
 related=[L("/cabs/delhi-to-shimla-taxi/","Delhi to Shimla taxi"),L("/cabs/chandigarh-to-manali-taxi/","Chandigarh to Manali taxi"),L("/cabs/chandigarh-to-shimla-taxi/","Chandigarh to Shimla taxi"),L("/escape-the-heat-and-recharge-the-ultimate-stress-free-weekend-getaway-to-himachal-pradesh-from-chandigarh/","Weekend getaways from Chandigarh")],
 wa="Hi Suzu Travels, I need a one-way taxi Delhi ⇄ Chandigarh. From: ___ , to: ___ , date & time: ___ , people: ___"),

# ------------------------------------------------------------------ DELHI -> DEHRADUN
dict(slug="delhi-to-dehradun-taxi", kind="route", route="delhi-to-dehradun-taxi",
 title="Delhi to Dehradun Taxi", seo_title="Delhi to Dehradun Taxi from ₹2,899 | Via New Expressway",
 seo_desc="Delhi to Dehradun taxi from ₹2,899 one-way via the new Delhi–Dehradun Expressway. Mussoorie, Rishikesh & Dehradun to Delhi drops too. WhatsApp quote.",
 focus="delhi to dehradun taxi",
 kicker="Delhi → Dehradun · New expressway",
 tag="Delhi to Dehradun taxi on the new expressway",
 sub="The Akshardham–Dehradun expressway makes this a half-day drive. Continue to Mussoorie, Rishikesh or Haridwar in the same cab.",
 answer="A Delhi to Dehradun taxi now takes about <b>4–5 hours door to door</b> (roughly 240 km from central Delhi) on the Delhi–Dehradun Expressway via Baghpat, Shamli and Saharanpur. One-way fares start around <b>₹2,899 for a sedan</b>, <b>₹3,499 for an Ertiga</b> and <b>₹4,899 for an Innova Crysta</b>; tolls are extra. Mussoorie is another 35 km, about 1.5 hours.",
 facts=[("Distance","~240 km"),("Drive time","4–5 hrs"),("Road","Delhi–Dehradun Expwy"),("Onward","Mussoorie · Rishikesh"),("Also","Dehradun → Delhi"),("Sedan from","₹2,899 one-way")],
 stops=[("Delhi","Pickup anywhere in Delhi NCR; the expressway starts near Akshardham."),
        ("Baghpat · Shamli","Access-controlled six-lane through western UP."),
        ("Saharanpur","Last stretch before the Shivaliks."),
        ("Rajaji elevated corridor","Elevated road over the wildlife corridor, then the Datkali tunnel."),
        ("Dehradun","Drop in Dehradun or Jolly Grant airport; Mussoorie 35 km further.")],
 map=dict(path=["Delhi","Baghpat","Shamli","Saharanpur","Dehradun"], labels=["Delhi","Baghpat","Shamli","Saharanpur","Dehradun"], ctx=["Mussoorie","Rishikesh","Haridwar"]),
 tips=[("Expressway tolls","The expressway is tolled; tolls are paid at actuals and shown in your quote."),("Uttarakhand permit","Cars registered outside Uttarakhand pay a state permit/entry fee where applicable — added at actuals."),("Mussoorie drops","Weekend traffic on the Mussoorie road is heavy; leave Dehradun before 10 am."),("Char Dham starts here","Dehradun, Haridwar and Rishikesh are the usual Char Dham starting points — see our <a href=\"/packages/ultimate-char-dham-yatra/\">Char Dham yatra</a>.")],
 faqs=[("What is the taxi fare from Delhi to Dehradun?","One-way starts around ₹2,899 for a sedan, ₹3,499 for an Ertiga, ₹3,899 for a Kia Carens and ₹4,899 for an Innova Crysta. Tolls and any state permit are extra at actuals."),
       ("How long is Delhi to Dehradun by the new expressway?","About 4–5 hours door to door from central Delhi, depending on city traffic at both ends."),
       ("Do you do Dehradun to Delhi taxis?","Yes, the same one-way fares apply from Dehradun, Mussoorie or Jolly Grant airport to Delhi NCR and IGI Airport."),
       ("Can we continue to Mussoorie?","Yes — add Mussoorie (35 km, about 1.5 hours) to the same booking."),
       ("Do you cover Rishikesh and Haridwar?","Yes, Delhi to Haridwar and Delhi to Rishikesh taxis are available at similar per-km fares."),
       ("Is a Tempo Traveller available for Dehradun?","Yes, 12–14 seat Tempo Travellers and Force Urbania vans for groups.")],
 related=[L("/uttarakhand/","Uttarakhand travel guide"),L("/tours/queen-of-hills-mussoorie/","Mussoorie tour package"),L("/tours/rishikesh-adventure-tour-package-4-days/","Rishikesh adventure package"),L("/destination/chardham-tour-packages/","Char Dham packages")],
 wa="Hi Suzu Travels, I need a Delhi to Dehradun taxi. Date: ___ , people: ___ , onward to Mussoorie/Rishikesh?: ___"),

# ------------------------------------------------------------------ DELHI -> HARIDWAR
dict(slug="delhi-to-haridwar-taxi", kind="route", route="delhi-to-haridwar-taxi",
 title="Delhi to Haridwar Taxi", seo_title="Delhi to Haridwar Taxi from ₹2,699 | One-Way Cab",
 seo_desc="Delhi to Haridwar taxi from ₹2,699 one-way, Innova Crysta from ₹4,499. 220 km, 4.5–5.5 hrs via Meerut. Airport pickup, Rishikesh drops, WhatsApp quote.",
 focus="delhi to haridwar taxi",
 kicker="Delhi → Haridwar · One-way & round trip",
 tag="Delhi to Haridwar taxi, in time for the Ganga Aarti",
 sub="Pickup from your home, hotel, IGI Airport or any Delhi station. Half a day on the Meerut expressway and NH-334, and you're on the ghats by afternoon.",
 answer="A Delhi to Haridwar taxi covers about <b>220 km in 4.5–5.5 hours</b> on the Delhi–Meerut Expressway and NH-334 via Meerut, Muzaffarnagar and Roorkee. One-way fares start around <b>₹2,699 for a sedan</b>, <b>₹3,199 for an Ertiga</b> and <b>₹4,499 for an Innova Crysta</b>; tolls and Uttarakhand's green cess are extra at actuals. Leave Delhi by 10 am to catch the evening aarti at Har Ki Pauri.",
 facts=[("Distance","~220 km"),("Drive time","4.5–5.5 hrs"),("Route","Delhi–Meerut Expwy → NH-334"),("Altitude","216 m → 314 m"),("Onward","Rishikesh +25 km"),("Sedan from","₹2,699 one-way")],
 stops=[("Delhi","Pickup from home, hotel, IGI Airport, New Delhi, Nizamuddin or Anand Vihar; Noida, Ghaziabad and Gurugram too."),
        ("Delhi–Meerut Expressway","Access-controlled run past Ghaziabad that skips most of the old NH-58 town traffic."),
        ("Meerut · Khatauli","The highway bypasses Meerut; Khatauli's big highway restaurants are the usual breakfast stop."),
        ("Muzaffarnagar","Bypass road around the city; about halfway in time."),
        ("Narsan border","Uttar Pradesh → Uttarakhand. Cameras here log the state's green cess — no stopping needed."),
        ("Roorkee","Old Ganga canal town; Piran Kaliyar dargah is a short detour."),
        ("Haridwar","Drop at your hotel, ashram, dharamshala or the railway station. Har Ki Pauri is reached on foot from the nearest parking.")],
 map=dict(path=["Delhi","Meerut","Khatauli","Muzaffarnagar","Narsan","Roorkee","Bahadarabad","Haridwar"], labels=["Delhi","Meerut","Muzaffarnagar","Roorkee","Haridwar"], ctx=["Rishikesh","Dehradun"]),
 tips=[("Kanwar Yatra weeks","During the Sawan Kanwar Yatra (30 July – 11 August in 2026) the Delhi–Haridwar highway was reserved for kanwariyas and closed to cars for about a week before Shivratri. In those weeks we route you via the Delhi–Dehradun Expressway or suggest other dates."),
       ("Uttarakhand green cess","Since 15 February 2026 out-of-state cars pay a small green cess (₹80 for light vehicles) logged by cameras at the border; CNG and electric cars are exempt. It is added to your quote at actuals, like the tolls."),
       ("Har Ki Pauri and the aarti","Cars cannot drive up to the ghat — the driver drops you at the nearest parking and you walk or take an e-rickshaw. The evening aarti is at sunset (about 5–5:30 pm in winter, 6:30–6:45 pm in summer); reach an hour early for a good spot."),
       ("Ardh Kumbh 2027","Haridwar's Ardh Kumbh brings huge crowds in March–April 2027, with main bathing days on 6 and 8 March and 14 April. Book cars early for those weeks and expect police drop points far from the ghats."),
       ("Onward to Rishikesh or Char Dham","Rishikesh is 25 km further and Dehradun about 55 km. For the Char Dham, online yatra registration is compulsory — see our <a href=\"/packages/ultimate-char-dham-yatra/\">Char Dham yatra</a>."),
       MONSOON],
 faqs=[("How much is a taxi from Delhi to Haridwar?","One-way fares start around ₹2,299 for a hatchback, ₹2,699 for a sedan, ₹3,199 for an Ertiga, ₹3,599 for a Kia Carens and ₹4,499 for an Innova Crysta. A 12-seater Tempo Traveller starts around ₹6,999. Tolls, parking and Uttarakhand's green cess are extra at actuals, and peak dates cost more."),
       ("How long does Delhi to Haridwar take by taxi?","About 4.5–5.5 hours for roughly 220 km, with one breakfast or tea stop. Weekend mornings, festival days and Kanwar season can add 1–3 hours."),
       ("Which route does the taxi take?","The Delhi–Meerut Expressway to Meerut, then NH-334 (the old NH-58) through Khatauli, Muzaffarnagar, Narsan and Roorkee. When that highway is closed for the Kanwar Yatra, we use the Delhi–Dehradun Expressway instead."),
       ("Is the Haridwar to Delhi fare the same?","Yes. The same one-way fares apply from any Haridwar hotel, ashram or the railway station to anywhere in Delhi NCR, including IGI Airport."),
       ("Can you pick me up from Delhi airport for Haridwar?","Yes, from IGI T1, T2 or T3. The driver waits at arrivals with your name and tracks your flight; plan about an extra hour for airport-side traffic."),
       ("Can we see the Ganga Aarti on the same day?","Yes, if you leave Delhi by about 10 am. The driver drops you at the nearest parking to Har Ki Pauri and waits, or drops you at your hotel first."),
       ("Is a same-day Delhi–Haridwar–Delhi round trip possible?","Yes, but it's a long 10–12 hour day. Round trips are billed per kilometre driven (a sedan is ₹12/km, 250 km daily minimum) plus ₹400 a night driver allowance if you stay over."),
       ("Can the same taxi continue to Rishikesh, Dehradun or the Char Dham?","Yes. Rishikesh is 25 km more and Dehradun about 55 km. For Char Dham trips we quote the whole 10–12 day circuit in one car.")],
 related=[L("/cabs/delhi-to-dehradun-taxi/","Delhi to Dehradun taxi"),L("/packages/ultimate-char-dham-yatra/","Char Dham yatra from Haridwar"),L("/tours/do-dham-gangotri-kedarnath-tour-from-haridwar/","Do Dham tour from Haridwar","Gangotri + Kedarnath"),L("/tours/rishikesh-adventure-tour-package-4-days/","Rishikesh adventure package"),L("/uttarakhand/","Uttarakhand tour packages")],
 wa="Hi Suzu Travels, I need a Delhi to Haridwar taxi. Date: ___ , people: ___ , one-way / round trip: ___"),

# ------------------------------------------------------------------ DELHI -> RISHIKESH
dict(slug="delhi-to-rishikesh-taxi", kind="route", route="delhi-to-rishikesh-taxi",
 title="Delhi to Rishikesh Taxi", seo_title="Delhi to Rishikesh Taxi from ₹2,899 | One-Way Cab",
 seo_desc="Delhi to Rishikesh taxi from ₹2,899 one-way, Innova Crysta from ₹4,899. About 240 km, 5–6 hrs via Haridwar. Tapovan, Shivpuri camp & airport drops.",
 focus="delhi to rishikesh taxi",
 kicker="Delhi → Rishikesh · One-way & round trip",
 tag="Delhi to Rishikesh taxi, door to Tapovan or your rafting camp",
 sub="Pickup from home, hotel, IGI Airport or any Delhi station. Breakfast on the highway, lunch by the Ganga.",
 answer="A Delhi to Rishikesh taxi covers about <b>240 km in 5–6 hours</b> on the Delhi–Meerut Expressway and NH-334 via Meerut, Muzaffarnagar, Roorkee and the Haridwar bypass. One-way fares start around <b>₹2,899 for a sedan</b>, <b>₹3,499 for an Ertiga</b> and <b>₹4,899 for an Innova Crysta</b>; tolls and Uttarakhand's green cess are extra at actuals. Shivpuri rafting camps are about 16 km further.",
 facts=[("Distance","~240 km"),("Drive time","5–6 hrs"),("Route","Meerut Expwy → NH-334"),("Drops","Tapovan · Ram Jhula · Shivpuri"),("Also","Rishikesh → Delhi"),("Sedan from","₹2,899 one-way")],
 stops=[("Delhi","Pickup from home, hotel, IGI Airport, New Delhi, Nizamuddin or Anand Vihar; Noida, Ghaziabad and Gurugram too."),
        ("Delhi–Meerut Expressway","Access-controlled start past Ghaziabad — the quickest way out of east Delhi in the morning."),
        ("Khatauli · Muzaffarnagar","The usual breakfast halt at the big highway restaurants; roughly the halfway mark."),
        ("Narsan border","Uttar Pradesh → Uttarakhand. Cameras log the green cess here; no stopping needed."),
        ("Roorkee","Canal town on the Upper Ganga Canal; the road narrows a little after this."),
        ("Haridwar bypass","The car skirts Haridwar's centre — add a Har Ki Pauri stop on the way if you like."),
        ("Raiwala · Rajaji forest belt","Last 20 km through the edge of Rajaji forest; keep an eye out for elephant warning signs."),
        ("Rishikesh","Drop in Tapovan, Laxman Jhula side, Ram Jhula / Swarg Ashram parking, AIIMS, the Yog Nagari station or your ashram. Shivpuri camps are about 16 km up the Badrinath road.")],
 map=dict(path=["Delhi","Meerut","Khatauli","Muzaffarnagar","Narsan","Roorkee","Bahadarabad","Haridwar","Rishikesh"], labels=["Delhi","Meerut","Muzaffarnagar","Roorkee","Haridwar","Rishikesh"], ctx=["Dehradun","Shivpuri"]),
 tips=[("Rafting season","The Ganga rafting season reopened in late September 2026 after the monsoon break. If you're heading to a Shivpuri camp, the driver can drop you right at the camp gate or the rafting start point — share the camp's location pin."),
       ("Ram Jhula and the ghats are on foot","Swarg Ashram, Parmarth Niketan and the old jhula bridges are pedestrian zones. The driver drops you at the nearest parking; the new Bajrang Setu next to the closed Laxman Jhula is open to walkers."),
       ("Uttarakhand green cess","Since 15 February 2026 out-of-state cars pay a small green cess (₹80 for light vehicles) logged by cameras at the border; CNG and electric cars are exempt. It is added at actuals, like the tolls."),
       ("Kanwar Yatra weeks","During the Sawan Kanwar Yatra (late July to early August) the Haridwar highway is closed to cars for several days. In those weeks we go via the Delhi–Dehradun Expressway and Doiwala, or suggest other dates."),
       ("Onward to the Char Dham","Rishikesh is the gateway to Badrinath and Kedarnath. Online yatra registration is compulsory — see our <a href=\"/packages/ultimate-char-dham-yatra/\">Char Dham yatra</a>."),
       MONSOON],
 faqs=[("What is the taxi fare from Delhi to Rishikesh?","One-way fares start around ₹2,499 for a hatchback, ₹2,899 for a sedan, ₹3,499 for an Ertiga, ₹3,899 for a Kia Carens and ₹4,899 for an Innova Crysta. A 12-seater Tempo Traveller starts around ₹6,999. Tolls, parking and Uttarakhand's green cess are extra at actuals; peak dates cost more."),
       ("How long does Delhi to Rishikesh take by car?","About 5–6 hours for roughly 240 km with one breakfast stop. Friday evenings, Sunday returns and festival days can add 1–2 hours, especially around Haridwar."),
       ("Is the Rishikesh to Delhi taxi fare the same?","Yes. The same one-way fares apply from Tapovan, Ram Jhula, a Shivpuri camp or Yog Nagari Rishikesh station to anywhere in Delhi NCR, including IGI Airport."),
       ("Can you drop us at our rafting camp in Shivpuri?","Yes. Shivpuri and the camps along the Badrinath road are about 16 km past Rishikesh; share the camp's location and the driver drops you at the gate."),
       ("Can I book a taxi from Delhi airport to Rishikesh?","Yes, from IGI T1, T2 or T3. The driver waits at arrivals with your name and tracks your flight; plan an extra hour for airport-side traffic."),
       ("Can we stop at Haridwar on the way?","Yes. Haridwar is on the route — a short stop for Har Ki Pauri adds about 1–2 hours. To catch the evening Ganga Aarti there, leave Delhi by about 10 am."),
       ("Is a same-day Delhi–Rishikesh–Delhi round trip possible?","It's possible but makes a long 11–12 hour day. Round trips are billed per kilometre driven (a sedan is ₹12/km, 250 km daily minimum) plus ₹400 a night driver allowance if you stay over."),
       ("Which route is better — via Meerut or the Dehradun Expressway?","For Rishikesh town the Meerut–Haridwar route is shorter. The Delhi–Dehradun Expressway via Doiwala suits Jolly Grant airport drops and the Kanwar weeks, when the Haridwar highway is closed.")],
 related=[L("/cabs/delhi-to-haridwar-taxi/","Delhi to Haridwar taxi"),L("/cabs/delhi-to-dehradun-taxi/","Delhi to Dehradun taxi"),L("/tours/rishikesh-adventure-tour-package-4-days/","Rishikesh adventure package","Rafting + stay"),L("/packages/ultimate-char-dham-yatra/","Char Dham yatra"),L("/uttarakhand/","Uttarakhand tour packages")],
 wa="Hi Suzu Travels, I need a Delhi to Rishikesh taxi. Date: ___ , people: ___ , drop (Tapovan / camp / hotel): ___"),

# ------------------------------------------------------------------ PATHANKOT -> DHARAMSHALA
dict(slug="pathankot-to-dharamshala-taxi", kind="route", route="pathankot-to-dharamshala-taxi",
 title="Pathankot to Dharamshala Taxi", seo_title="Pathankot to Dharamshala Taxi from ₹2,299 | Station Pickup",
 seo_desc="Pathankot to Dharamshala & McLeodganj taxi from ₹2,299 one-way. Pathankot station & airport pickup, 90 km in 2.5–3 hrs. Dalhousie drops too.",
 focus="pathankot to dharamshala taxi",
 kicker="Pathankot → Dharamshala · Station pickup",
 tag="Pathankot to Dharamshala & McLeodganj taxi",
 sub="Train into Pathankot or Chakki Bank, and a cab waiting at the exit. Two and a half hours to the Dhauladhars.",
 answer="A Pathankot to Dharamshala taxi covers about <b>90 km in 2.5–3 hours</b> via Nurpur, Shahpur and Gaggal (Kangra airport); McLeodganj is 10 km further. One-way fares start around <b>₹2,299 for a sedan</b>, <b>₹2,999 for an Ertiga</b> and <b>₹3,999 for an Innova Crysta</b>. Pathankot to Dalhousie (about 80 km, 2.5–3 hours) is available at similar fares.",
 facts=[("Distance","~90 km"),("Drive time","2.5–3 hrs"),("Pickup","Pathankot Jn · Chakki Bank"),("McLeodganj","+10 km"),("Also","Pathankot → Dalhousie"),("Sedan from","₹2,299 one-way")],
 stops=[("Pathankot","Pathankot Junction, Chakki Bank station, Pathankot airport or bus stand."),
        ("Nurpur","Old Nurpur fort on the hill."),
        ("Shahpur","The Kangra valley opens up with Dhauladhar views."),
        ("Gaggal","Kangra airport — drops and pickups too."),
        ("Dharamshala · McLeodganj","Drop in lower Dharamshala, McLeodganj, Bhagsu or Dharamkot.")],
 map=dict(path=["Pathankot","Nurpur","Shahpur","Gaggal","Dharamshala"], labels=["Pathankot","Nurpur","Shahpur","Gaggal","Dharamshala"], ctx=["Dalhousie","Kangra"]),
 tips=[("Train timing","Overnight trains reach Pathankot early morning; the driver waits outside with your name. Share the train number."),HP_ENTRY,("McLeodganj lanes","Some McLeodganj lanes are one-way or narrow; we drop at the closest point to your hotel."),("Add Dalhousie","Pathankot → Dalhousie → Khajjiar → Dharamshala is a popular 3–4 day circuit in one cab.")],
 faqs=[("How much is a taxi from Pathankot to Dharamshala?","One-way starts around ₹2,299 for a sedan, ₹2,999 for an Ertiga and ₹3,999 for an Innova Crysta. Tolls, parking and the Himachal entry fee are extra at actuals."),
       ("How far is Dharamshala from Pathankot?","About 90 km — 2.5 to 3 hours by car. McLeodganj is 10 km above Dharamshala."),
       ("Can you pick us up at Pathankot or Chakki Bank station?","Yes, from both stations and Pathankot airport; the driver tracks your train."),
       ("What is the Pathankot to Dalhousie taxi fare?","Around the same as Dharamshala for a similar distance: sedans start around ₹2,299 one-way."),
       ("Do you drop at Kangra (Gaggal) airport?","Yes, Dharamshala to Gaggal airport and Pathankot to Gaggal drops are available."),
       ("Can I book a Dharamshala–Dalhousie tour in the same cab?","Yes, multi-day tours are billed per kilometre with a 250 km daily minimum plus driver allowance.")],
 related=[L("/destination/dharamshala-tour-packages/","Dharamshala packages"),L("/tours/magnificent-dharamshala-dalhousie-tour-package-from-pathankot/","Dharamshala–Dalhousie from Pathankot","Hotel + cab"),L("/dalhousie/","Dalhousie guide"),L("/dharamshala-tour-package-from-delhi/","Dharamshala package from Delhi")],
 wa="Hi Suzu Travels, I need a Pathankot to Dharamshala taxi. Train/flight: ___ , date: ___ , people: ___"),

# ------------------------------------------------------------------ JAMMU -> SRINAGAR
dict(slug="jammu-to-srinagar-taxi", kind="route", route="jammu-to-srinagar-taxi",
 title="Jammu to Srinagar Taxi", seo_title="Jammu to Srinagar Taxi from ₹5,999 | Fare 2026",
 seo_desc="Jammu to Srinagar taxi fare 2026: sedan from ₹5,999, Innova Crysta from ₹10,199. 250 km via Banihal tunnels, 6–8 hrs. Jammu Tawi & Katra pickup.",
 focus="jammu to srinagar taxi",
 kicker="Jammu → Srinagar · Through the tunnels",
 tag="Jammu to Srinagar by taxi, through the Banihal tunnels",
 sub="Pickup at Jammu Tawi, Jammu airport or Katra. A J&K-registered cab and a driver who knows the highway advisories.",
 answer="A Jammu to Srinagar taxi covers about <b>250 km in 6–8 hours</b> on NH44 via Udhampur, the Chenani–Nashri tunnel, Ramban, Banihal and the Banihal–Qazigund tunnel. One-way fares start around <b>₹5,999 for a sedan</b> and <b>₹10,199 for an Innova Crysta</b>. Traffic advisories and one-way regulation can change timings, so we confirm the start time the evening before.",
 facts=[("Distance","~250 km"),("Drive time","6–8 hrs"),("Road","NH44 via Banihal"),("Pickup","Jammu Tawi · airport · Katra"),("Tunnels","Chenani–Nashri · Banihal"),("Sedan from","₹5,999 one-way")],
 stops=[("Jammu","Jammu Tawi station, Jammu airport, bus stand or your hotel; Katra pickups on request."),
        ("Nagrota · Udhampur","Climb begins; Patnitop is a detour off the tunnel road."),
        ("Chenani–Nashri tunnel","The 9 km Dr Syama Prasad Mookerjee tunnel."),
        ("Ramban · Banihal","The Chenab gorge — the stretch most affected by weather."),
        ("Banihal–Qazigund tunnel","Into the Kashmir valley."),
        ("Anantnag · Pampore","Saffron fields at Pampore."),
        ("Srinagar","Drop at your houseboat ghat or hotel.")],
 map=dict(path=["Jammu","Nagrota","Udhampur","Ramban","Banihal","Qazigund","Anantnag","Pampore","Srinagar"], labels=["Jammu","Udhampur","Ramban","Banihal","Qazigund","Srinagar"], ctx=["Katra","Pathankot","Leh"]),
 tips=[("Highway advisories","The Jammu–Srinagar highway sometimes runs one-way or closes after rain or snow. We check the J&K traffic advisory and confirm your start time the evening before."),("Local Kashmir taxis","Gulmarg, Pahalgam and Sonamarg sightseeing uses Kashmir-registered local taxis (union practice). We book them for you at local rates."),("Train option","Many travellers now take the Katra–Srinagar train. We can pick you up at Srinagar or Katra station instead."),NIGHT],
 faqs=[("What is the Jammu to Srinagar taxi fare in 2026?","One-way starts around ₹5,999 for a sedan, ₹7,299 for an Ertiga and ₹10,199 for an Innova Crysta. Tolls and parking are extra; peak-season dates cost more."),
       ("How long does Jammu to Srinagar take by road?","6–8 hours for about 250 km, depending on traffic regulation and weather around Ramban and Banihal."),
       ("Can you pick us up from Katra?","Yes, Katra to Srinagar drops are available; the fare depends on the date and car."),
       ("Is the Jammu–Srinagar highway open in winter?","Mostly yes, but heavy snow or landslides can close it for a day or more. We watch advisories and adjust the plan."),
       ("Can the same taxi do Gulmarg and Pahalgam?","Sightseeing inside Kashmir is done in local Kashmir-registered taxis as per union practice; we book them for you."),
       ("Do you have Kashmir tour packages with cabs?","Yes — see our Kashmir packages; they include all transfers.")],
 related=[L("/destination/kashmir-tour-packages/","Kashmir tour packages"),L("/best-kashmir-tour-package/","How to choose a Kashmir package"),L("/kashmir-best-time-visit-planning-guide-2026/","Best time to visit Kashmir"),L("/kashmir-dmc/","Kashmir DMC for agents")],
 wa="Hi Suzu Travels, I need a Jammu to Srinagar taxi. Pickup (station/airport/Katra): ___ , date: ___ , people: ___"),

# ------------------------------------------------------------------ MANALI TAXI SERVICE
dict(slug="manali-taxi-service", kind="city", route=None,
 title="Manali Taxi Service", seo_title="Manali Taxi Service 2026 | Solang, Rohtang & Atal Tunnel",
 seo_desc="Manali taxi service: local sightseeing, Solang, Atal Tunnel–Sissu & Rohtang at 2026 union rates, plus Manali to Chandigarh, Delhi, Kasol, Leh & Spiti cabs.",
 focus="manali taxi service",
 kicker="Manali · Local sightseeing & outstation",
 tag="Manali taxis for snow days, sightseeing and drops",
 sub="Solang, Atal Tunnel–Sissu and Rohtang in Manali-registered local taxis at union rates — plus outstation cabs to Chandigarh, Delhi, Kasol, Spiti and Leh.",
 answer="In Manali, <b>local sightseeing (Solang, Atal Tunnel–Sissu, Rohtang) runs in Manali-registered union taxis</b>. Published 2026 union rates are around <b>₹2,499 (sedan) for Solang</b>, <b>₹3,499 for Atal Tunnel + Sissu</b> and <b>₹4,999 for Rohtang</b>, plus the Rohtang permit. We book these for you, and also run outstation cabs from Manali to Chandigarh, Delhi, Kasol, Spiti and Leh.",
 facts=[("Solang","~14 km"),("Atal Tunnel","~25 km"),("Rohtang","~51 km, permit"),("Bhuntar airport","~50 km"),("Rohtang shut","Tuesdays"),("Snow","Dec – Feb")],
 stops=[("Manali town","Hadimba temple, Vashisht hot springs, Manu temple, Old Manali, Club House."),
        ("Solang Valley","Ropeway, paragliding, snow play in winter."),
        ("Atal Tunnel · Sissu","9 km tunnel to Lahaul; Sissu waterfall and snow."),
        ("Rohtang Pass","Online permit needed; usually open about May–November."),
        ("Naggar","Naggar castle and the Roerich gallery, 22 km."),
        ("Kasol · Manikaran","Parvati valley, 75 km via Bhuntar.")],
 map=dict(hub="Manali", spokes=["Solang","Sissu","Rohtang","Naggar","Kasol","Bhuntar"], ctx=["Kullu","Mandi","Keylong"]),
 local_rates=dict(head=["Trip (from Manali)","Hatchback","Sedan","SUV / Innova"], note="Indicative 2026 Manali taxi-union rates from published rate lists; confirmed on your quote. Rohtang permit (about ₹550 per vehicle) is extra.",
   rows=[("Manali local sightseeing (full day)","₹1,999","₹2,499","₹2,999"),("Solang Valley","₹1,999","₹2,499","₹2,999"),("Atal Tunnel + Sissu","₹2,999","₹3,499","₹4,999"),("Rohtang Pass (with permit day)","₹3,999","₹4,999","₹6,999"),("Naggar castle & Jana waterfall","On quote","On quote","On quote"),("Manikaran + Kasol day trip","On quote","On quote","On quote")]),
 outstation=[("Manali","Chandigarh",290,1.1),("Manali","Delhi",540,1.0),("Manali","Shimla",245,1.1),("Manali","Kasol",75,1.1),("Manali","Dharamshala",235,1.1),("Manali","Leh",430,1.6)],
 tips=[("Why a local taxi for Solang & Rohtang?","By long-standing Manali union practice, sightseeing to Solang, Atal Tunnel and Rohtang is done in Manali-registered taxis. Outside cabs drop you in Manali; we book the local taxi so you don't have to bargain."),("Rohtang permit","Rohtang needs an online permit (rohtangpermits.nic.in) with a daily vehicle cap, and the pass is closed on Tuesdays. We apply for it with the local taxi."),WINTER,("Snow gear","Snow suits and boots are rented on the Solang / Palchan road; the driver stops at a shop you choose.")],
 faqs=[("How much does a taxi for Manali sightseeing cost?","A full day of Manali local sightseeing is around ₹2,499 in a sedan. Solang is around ₹2,499, Atal Tunnel + Sissu around ₹3,499 and Rohtang around ₹4,999 in a sedan (2026 union rates, indicative). The Rohtang permit is extra."),
       ("What is the Manali to Rohtang taxi fare?","Around ₹3,999 in a hatchback, ₹4,999 in a sedan and ₹6,999 in an SUV/Innova, plus the online Rohtang permit. Rohtang is closed on Tuesdays and usually open from about May to November."),
       ("Can an outside taxi go to Solang or Rohtang?","Local union practice is that sightseeing is done in Manali-registered taxis. We book the local taxi for you so your trip isn't held up."),
       ("Do you provide Manali to Chandigarh and Delhi taxis?","Yes. Manali to Chandigarh starts around ₹4,499 and Manali to Delhi around ₹7,599 for a sedan, one-way."),
       ("Is there a taxi from Bhuntar (Kullu) airport to Manali?","Yes, airport pickups at Bhuntar are available; the driver tracks your flight."),
       ("Can I get a taxi from Manali to Leh or Spiti?","Yes, from about June to October for Leh, and for Spiti via Kunzum when the pass is open. High-altitude trips are quoted per day.")],
 related=[L("/manali/","Manali travel guide"),L("/adventure/snow-activities-manali/","Snow activities in Manali"),L("/cabs/chandigarh-to-manali-taxi/","Chandigarh to Manali taxi"),L("/cabs/delhi-to-manali-taxi/","Delhi to Manali taxi"),L("/packages/kullu-manali-honeymoon-tour-package/","Kullu–Manali honeymoon package")],
 wa="Hi Suzu Travels, I need a taxi in Manali. Trip (Solang/Atal Tunnel/Rohtang/drop): ___ , date: ___ , people: ___"),

# ------------------------------------------------------------------ SHIMLA TAXI SERVICE
dict(slug="shimla-taxi-service", kind="city", route=None,
 title="Shimla Taxi Service", seo_title="Shimla Taxi Service 2026 | Kufri, Chail & Narkanda Trips",
 seo_desc="Shimla taxi service for Kufri, Chail, Naldehra & Narkanda sightseeing, Kalka & Chandigarh airport transfers, and drops to Manali or Delhi.",
 focus="shimla taxi service",
 kicker="Shimla · Sightseeing & transfers",
 tag="Shimla taxis for Kufri, Chail, Narkanda and every drop",
 sub="Day trips around Shimla, pickups at Kalka station, Shimla airport or Chandigarh, and one-way drops to Manali, Delhi and beyond.",
 answer="A <b>Shimla taxi for local sightseeing</b> (Kufri, Fagu, Mashobra, Naldehra) typically costs <b>₹2,500–3,000 a day</b> in a sedan; <b>Chail or Narkanda</b> day trips run about <b>₹3,000–3,500</b>. We also do Kalka station and Chandigarh airport transfers and one-way drops from Shimla to Manali (from about ₹3,799) and Delhi (from about ₹4,899).",
 facts=[("Kufri","~16 km"),("Naldehra","~23 km"),("Chail","~45 km"),("Narkanda","~60 km"),("Kalka station","~85 km"),("Snow","Dec – Feb")],
 stops=[("Shimla","Pickup from your hotel's nearest road point."),
        ("Kufri · Fagu","Horse and yak rides, apple orchards, snow in winter."),
        ("Mashobra · Naldehra","Pine forests and the old golf course."),
        ("Chail","Chail palace and the high cricket ground."),
        ("Narkanda","Hatu peak and winter skiing slopes."),
        ("Kalka · Chandigarh","Station and airport transfers.")],
 map=dict(hub="Shimla", spokes=["Kufri","Naldehra","Chail","Narkanda","Kasauli","Kalka"], ctx=["Solan","Chandigarh","Mashobra"]),
 local_rates=dict(head=["Trip (from Shimla)","Sedan","Ertiga / SUV","Innova Crysta"], note="Indicative day-trip rates; the exact fare depends on date, hours and stops and is confirmed on your quote.",
   rows=[("Shimla local sightseeing (full day)","₹2,500","₹3,000","₹3,500"),("Kufri · Fagu · Mashobra","₹2,500","₹3,000","₹3,500"),("Chail day trip","₹3,000","₹3,500","₹4,000"),("Narkanda · Hatu peak","₹3,000","₹3,500","₹4,500"),("Naldehra · Tattapani","On quote","On quote","On quote"),("Shimla ⇄ Kalka station","₹2,299","₹2,999","₹3,999")]),
 outstation=[("Shimla","Chandigarh",115,1.1),("Shimla","Delhi",345,1.0),("Shimla","Manali",245,1.1),("Shimla","Dharamshala",235,1.1),("Shimla","Kasauli",70,1.1),("Shimla","Narkanda",60,1.1)],
 tips=[("Sealed roads","The Mall, Ridge and several core lanes are closed to cars. We pick up from the nearest allowed point (Lift, Victory Tunnel, Cart Road)."),("Kufri in winter","After fresh snow the Kufri road can jam or close; go early and keep a flexible day."),HP_ENTRY,("Toy train combo","Ride the Kalka–Shimla toy train one way and let the cab carry your luggage — ask for the combo.")],
 faqs=[("How much is a taxi for Shimla sightseeing?","A full day of Shimla local sightseeing costs around ₹2,500 in a sedan and ₹3,500 in an Innova Crysta. Chail and Narkanda day trips are around ₹3,000–4,500 depending on the car."),
       ("What is the Shimla to Kufri taxi fare?","A Kufri–Fagu–Mashobra half/full day runs about ₹2,500 in a sedan. Horse and yak rides at Kufri are paid separately."),
       ("Do you have Shimla to Manali taxis?","Yes, one-way Shimla to Manali starts around ₹3,799 for a sedan; the drive is about 7–8 hours via Mandi."),
       ("Can you pick us up from Kalka railway station?","Yes, Kalka to Shimla transfers start around ₹2,299 for a sedan (about 85 km, 2.5–3 hours)."),
       ("Is there a taxi from Shimla to Chandigarh airport?","Yes, drops to IXC airport and Chandigarh railway station; we plan the time around your flight."),
       ("Can taxis go on the Mall Road?","No, the Mall Road and Ridge are car-free zones. Hotels there are reached on foot or by the public lift.")],
 related=[L("/shimla/","Shimla travel guide"),L("/best-time-to-visit-shimla/","Best time to visit Shimla"),L("/cabs/chandigarh-to-shimla-taxi/","Chandigarh to Shimla taxi"),L("/cabs/delhi-to-shimla-taxi/","Delhi to Shimla taxi"),L("/packages/unexplored-kinnaur-tour-package-from-shimla/","Kinnaur tour from Shimla")],
 wa="Hi Suzu Travels, I need a taxi in Shimla. Trip (Kufri/Chail/Narkanda/drop): ___ , date: ___ , people: ___"),

# ------------------------------------------------------------------ TEMPO TRAVELLER DELHI
dict(slug="tempo-traveller-hire-delhi", kind="vehicle", vehicle="tempo", route=None,
 title="Tempo Traveller Hire in Delhi", seo_title="Tempo Traveller Hire in Delhi | 12–17 Seater from ₹26/km",
 seo_desc="Tempo Traveller on rent in Delhi: 12–14 seater from ₹26/km and Force Urbania for 17. Himachal, Char Dham, Haridwar & Vaishno Devi trips. WhatsApp quote.",
 focus="tempo traveller hire in delhi",
 kicker="Delhi NCR · 12 to 17 seats",
 tag="Tempo Traveller hire in Delhi for hills, pilgrimages and weddings",
 sub="Force Tempo Traveller (12–14 seats) and Force Urbania (up to 17) with pushback seats, AC and roof carrier. Outstation trips from Delhi NCR across North India.",
 answer="Tempo Traveller hire in Delhi starts around <b>₹26 per km for a 12–14 seater</b> (minimum 250 km a day) plus <b>₹500 a night driver allowance</b>; a Force Urbania for up to 17 people starts around ₹36 per km. Tolls, parking and state permits are extra at actuals. Popular trips: Shimla–Manali, Haridwar–Rishikesh, Char Dham and Vaishno Devi.",
 facts=[("12–14 seater","from ₹26/km"),("Urbania 17","from ₹36/km"),("Minimum","250 km / day"),("Driver","₹500 / night"),("Pickup","All Delhi NCR"),("One-way","Hill drops too")],
 stops=[("Shimla · Manali","Delhi → Shimla → Manali → Delhi, 6–7 days."),
        ("Haridwar · Rishikesh","Weekend ganga aarti and rafting trips."),
        ("Char Dham","10–12 days via Haridwar or Dehradun."),
        ("Vaishno Devi (Katra)","Overnight drive or with an Amritsar stop."),
        ("Dharamshala · Dalhousie","Via Chandigarh or Pathankot."),
        ("Agra · Jaipur","Golden Triangle for family groups.")],
 map=dict(hub="Delhi", spokes=["Shimla","Manali","Dharamshala","Rishikesh","Dehradun","Amritsar","Katra"], ctx=["Chandigarh","Haridwar","Agra"]),
 tips=[("State permits","Tempo Travellers pay a state permit/tax when they enter Himachal, Uttarakhand, Punjab or J&K. It's charged at actuals and shown in your quote."),("Luggage","12 people need a roof carrier and a tarpaulin in rain; both are included."),NIGHT,("Luxury options","Maharaja-seat Tempo Travellers and 20–26 seaters can be arranged on request.")],
 faqs=[("What is the Tempo Traveller rent per km in Delhi?","From about ₹26 per km for a 12–14 seat Force Tempo Traveller and about ₹36 per km for a Force Urbania, with a 250 km daily minimum and ₹500 a night driver allowance."),
       ("How much is a Tempo Traveller from Delhi to Shimla or Manali?","One-way Delhi to Shimla starts around ₹11,099 and Delhi to Manali around ₹17,299 for a 12-seater. A 6-day Shimla–Manali round trip is billed per km."),
       ("What's included in the Tempo Traveller fare?","Vehicle, fuel and driver. Tolls, parking, state permits and the driver's night allowance are added as per your quote."),
       ("Is a 12 seater enough for 12 adults with luggage?","It's comfortable for 10–11 adults with bags; for 12 adults with heavy luggage choose the Urbania or two vehicles."),
       ("Do you have 16 or 20 seater Tempo Travellers?","Yes, on request; availability depends on the date."),
       ("Can we book a Tempo Traveller for Char Dham from Delhi?","Yes, with a driver experienced on the Char Dham routes. Book early for May–June.")],
 related=[L("/tours/tempo-traveller-force/","Tempo Traveller (vehicle page)"),L("/packages/ultimate-char-dham-yatra/","Char Dham yatra package"),L("/himachal-tour-packages/","Himachal tour packages"),L("/tours/amazing-kashmir-vaishno-devi-package/","Kashmir + Vaishno Devi")],
 wa="Hi Suzu Travels, I need a Tempo Traveller from Delhi. Seats: ___ , trip: ___ , dates: ___"),

# ------------------------------------------------------------------ INNOVA CRYSTA
dict(slug="innova-crysta-on-rent", kind="vehicle", vehicle="crysta", route=None,
 title="Innova Crysta on Rent with Driver", seo_title="Innova Crysta on Rent with Driver | From ₹19/km",
 seo_desc="Innova Crysta on rent with driver from ₹19/km: Delhi & Chandigarh pickups for Shimla, Manali, Kashmir and Char Dham trips. One-way drops too. Get a quote.",
 focus="innova crysta on rent",
 kicker="Innova Crysta · With driver",
 tag="Innova Crysta on rent with a hill-trained driver",
 sub="The most asked-for car for Himachal and Uttarakhand family trips — 6+1 or 7 seats, rear AC and room for five bags. Outstation from Delhi, Chandigarh and Pathankot.",
 answer="An <b>Innova Crysta on rent with driver</b> starts around <b>₹19 per km</b> for round trips and tours (minimum 250 km a day) plus ₹400 a night driver allowance. One-way hill drops start around ₹8,299 Delhi–Shimla, ₹7,699 Chandigarh–Manali and ₹12,999 Delhi–Manali. Tolls, parking and state entry fees are extra at actuals.",
 facts=[("Round trip","from ₹19/km"),("Minimum","250 km / day"),("Driver","₹400 / night"),("Seats","6+1 or 7"),("Luggage","~5 bags"),("Self-drive","Not offered")],
 stops=[("Delhi → Shimla → Manali","The classic 6–7 day family circuit."),
        ("Chandigarh → Manali","One-way or with a Kasol day."),
        ("Pathankot → Dalhousie → Dharamshala","3–4 days in the Kangra valley."),
        ("Delhi → Char Dham","10–12 days, senior-citizen friendly."),
        ("Jammu → Srinagar","Kashmir arrivals and drops."),
        ("Delhi → Amritsar","Golden Temple and Wagah.")],
 map=dict(hub="Delhi", spokes=["Shimla","Manali","Dharamshala","Dehradun","Amritsar","Katra"], ctx=["Chandigarh","Srinagar","Haridwar"]),
 tips=[("Crysta vs Ertiga","For 5+ adults with luggage on hill roads the Crysta's diesel torque, rear AC and ride comfort make a real difference; for 4 people with light bags an Ertiga saves money."),HP_ENTRY,NIGHT,("Captain seats","Want the 6+1 captain-seat version for elders? Ask when you book.")],
 faqs=[("What is the Innova Crysta rent per km?","About ₹19 per km for round trips and multi-day tours, with a 250 km daily minimum and ₹400 a night driver allowance. Tolls, parking and state entry fees are extra."),
       ("What is the Innova Crysta rent per day?","It works out to about ₹4,750 a day (250 km × ₹19) plus driver allowance on a multi-day tour. Local city use is quoted separately."),
       ("How much is an Innova Crysta one-way from Delhi to Manali?","From about ₹12,999; Delhi to Shimla from about ₹8,299 and Chandigarh to Manali from about ₹7,699."),
       ("How many people fit in an Innova Crysta?","Six passengers comfortably (6+1 captain seats) or seven in the bench version, with about five medium bags."),
       ("Do you give Innova Crysta on self-drive?","No, all our cars come with a driver."),
       ("Is Innova Hycross or Fortuner available?","On request for some dates; ask on WhatsApp.")],
 related=[L("/tours/innova-crysta/","Innova Crysta (vehicle page)"),L("/tours/innova-crysta-71/","Innova Crysta 7+1"),L("/cabs/delhi-to-manali-taxi/","Delhi to Manali taxi"),L("/himachal-tour-packages/","Himachal tour packages")],
 wa="Hi Suzu Travels, I want an Innova Crysta with driver. Trip: ___ , dates: ___ , people: ___"),
]
